# ./parameters/production/parameters.yaml
AzureDataLakeStorage_ls_myurl: https://stbiseuw.dfs.core.windows.net
Notebook_properties_bigDataPool_referenceName: sparkpoolprod
Notebook2_properties_bigDataPool_referenceName: sparkpoolprod
