# ./parameters/production/parameters.yaml
AzureDataLakeStorage_ls_myurl: https://stbiseuw.dfs.core.windows.net
synw-bis-dev-WorkspaceDefaultStorage_myurl: https://stbiseuw.dfs.core.windows.net
Notebook_properties_bigDataPool_referenceName: sparkpool
Notebook2_properties_bigDataPool_referenceName: sparkpool
